// SPDX-FileCopyrightText: Copyright 2020 yuzu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include <string>

#include <fmt/ranges.h>

#include "video_core/surface.h"
#include "video_core/texture_cache/types.h"

template <>
struct fmt::formatter<VideoCore::Surface::PixelFormat> : fmt::formatter<fmt::string_view> {
    template <typename FormatContext>
    auto format(VideoCore::Surface::PixelFormat format, FormatContext& ctx) const {
        using VideoCore::Surface::PixelFormat;
        const string_view name = [format] {
            switch (format) {
#define FMT_PIXEL_FORMAT_LIST
    FMT_PIXEL_FORMAT_ELEM(A8B8G8R8_UNORM) /*A8B8G8R8_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(A8B8G8R8_SNORM) /*A8B8G8R8_SNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(A8B8G8R8_SINT) /*A8B8G8R8_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(A8B8G8R8_UINT) /*A8B8G8R8_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R5G6B5_UNORM) /*R5G6B5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(B5G6R5_UNORM) /*B5G6R5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(A1R5G5B5_UNORM) /*A1R5G5B5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(A2B10G10R10_UNORM) /*A2B10G10R10_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(A2B10G10R10_UINT) /*A2B10G10R10_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(A2R10G10B10_UNORM) /*A2R10G10B10_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(A1B5G5R5_UNORM) /*A1B5G5R5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(A5B5G5R1_UNORM) /*A5B5G5R1_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R8_UNORM) /*R8_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R8_SNORM) /*R8_SNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R8_SINT) /*R8_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R8_UINT) /*R8_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16B16A16_FLOAT) /*R16G16B16A16_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16B16A16_UNORM) /*R16G16B16A16_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16B16A16_SNORM) /*R16G16B16A16_SNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16B16A16_SINT) /*R16G16B16A16_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16B16A16_UINT) /*R16G16B16A16_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(B10G11R11_FLOAT) /*B10G11R11_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(R32G32B32A32_UINT) /*R32G32B32A32_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(BC1_RGBA_UNORM) /*BC1_RGBA_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(BC2_UNORM) /*BC2_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(BC3_UNORM) /*BC3_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(BC4_UNORM) /*BC4_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(BC4_SNORM) /*BC4_SNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(BC5_UNORM) /*BC5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(BC5_SNORM) /*BC5_SNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(BC7_UNORM) /*BC7_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(BC6H_UFLOAT) /*BC6H_UFLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(BC6H_SFLOAT) /*BC6H_SFLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_4X4_UNORM) /*ASTC_2D_4X4_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(B8G8R8A8_UNORM) /*B8G8R8A8_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R32G32B32A32_FLOAT) /*R32G32B32A32_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(R32G32B32A32_SINT) /*R32G32B32A32_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R32G32_FLOAT) /*R32G32_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(R32G32_SINT) /*R32G32_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R32_FLOAT) /*R32_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16_FLOAT) /*R16_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16_UNORM) /*R16_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R16_SNORM) /*R16_SNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R16_UINT) /*R16_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16_SINT) /*R16_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16_UNORM) /*R16G16_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16_FLOAT) /*R16G16_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16_UINT) /*R16G16_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16_SINT) /*R16G16_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16_SNORM) /*R16G16_SNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R32G32B32_FLOAT) /*R32G32B32_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(A8B8G8R8_SRGB) /*A8B8G8R8_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(R8G8_UNORM) /*R8G8_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R8G8_SNORM) /*R8G8_SNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(R8G8_SINT) /*R8G8_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R8G8_UINT) /*R8G8_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R32G32_UINT) /*R32G32_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R16G16B16X16_FLOAT) /*R16G16B16X16_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(R32_UINT) /*R32_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(R32_SINT) /*R32_SINT*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_8X8_UNORM) /*ASTC_2D_8X8_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_8X5_UNORM) /*ASTC_2D_8X5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_5X4_UNORM) /*ASTC_2D_5X4_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(B8G8R8A8_SRGB) /*B8G8R8A8_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(BC1_RGBA_SRGB) /*BC1_RGBA_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(BC2_SRGB) /*BC2_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(BC3_SRGB) /*BC3_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(BC7_SRGB) /*BC7_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(A4B4G4R4_UNORM) /*A4B4G4R4_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(G4R4_UNORM) /*G4R4_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_4X4_SRGB) /*ASTC_2D_4X4_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_8X8_SRGB) /*ASTC_2D_8X8_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_8X5_SRGB) /*ASTC_2D_8X5_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_5X4_SRGB) /*ASTC_2D_5X4_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_5X5_UNORM) /*ASTC_2D_5X5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_5X5_SRGB) /*ASTC_2D_5X5_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_10X8_UNORM) /*ASTC_2D_10X8_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_10X8_SRGB) /*ASTC_2D_10X8_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_6X6_UNORM) /*ASTC_2D_6X6_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_6X6_SRGB) /*ASTC_2D_6X6_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_10X6_UNORM) /*ASTC_2D_10X6_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_10X6_SRGB) /*ASTC_2D_10X6_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_10X5_UNORM) /*ASTC_2D_10X5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_10X5_SRGB) /*ASTC_2D_10X5_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_10X10_UNORM) /*ASTC_2D_10X10_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_10X10_SRGB) /*ASTC_2D_10X10_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_12X10_UNORM) /*ASTC_2D_12X10_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_12X10_SRGB) /*ASTC_2D_12X10_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_12X12_UNORM) /*ASTC_2D_12X12_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_12X12_SRGB) /*ASTC_2D_12X12_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_8X6_UNORM) /*ASTC_2D_8X6_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_8X6_SRGB) /*ASTC_2D_8X6_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_6X5_UNORM) /*ASTC_2D_6X5_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(ASTC_2D_6X5_SRGB) /*ASTC_2D_6X5_SRGB*/ \
    FMT_PIXEL_FORMAT_ELEM(E5B9G9R9_FLOAT) /*E5B9G9R9_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(D32_FLOAT) /*D32_FLOAT*/ \
    FMT_PIXEL_FORMAT_ELEM(D16_UNORM) /*D16_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(X8_D24_UNORM) /*X8_D24_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(S8_UINT) /*S8_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(D24_UNORM_S8_UINT) /*D24_UNORM_S8_UINT*/ \
    FMT_PIXEL_FORMAT_ELEM(S8_UINT_D24_UNORM) /*S8_UINT_D24_UNORM*/ \
    FMT_PIXEL_FORMAT_ELEM(D32_FLOAT_S8_UINT) /*D32_FLOAT_S8_UINT*/ \
#define FMT_PIXEL_FORMAT_ELEM(NAME) case PixelFormat::NAME: return #NAME;
    FMT_PIXEL_FORMAT_LIST
#undef FMT_PIXEL_FORMAT_ELEM
#undef FMT_PIXEL_FORMAT_LIST
            case PixelFormat::MaxDepthStencilFormat:
            case PixelFormat::Invalid:
                return "Invalid";
            }
            return "Invalid";
        }();
        return formatter<string_view>::format(name, ctx);
    }
};

template <>
struct fmt::formatter<VideoCommon::ImageType> : fmt::formatter<fmt::string_view> {
    template <typename FormatContext>
    auto format(VideoCommon::ImageType type, FormatContext& ctx) const {
        const string_view name = [type] {
            using VideoCommon::ImageType;
            switch (type) {
            case ImageType::e1D:
                return "1D";
            case ImageType::e2D:
                return "2D";
            case ImageType::e3D:
                return "3D";
            case ImageType::Linear:
                return "Linear";
            case ImageType::Buffer:
                return "Buffer";
            }
            return "Invalid";
        }();
        return formatter<string_view>::format(name, ctx);
    }
};

template <>
struct fmt::formatter<VideoCommon::Extent3D> {
    constexpr auto parse(fmt::format_parse_context& ctx) {
        return ctx.begin();
    }

    template <typename FormatContext>
    auto format(const VideoCommon::Extent3D& extent, FormatContext& ctx) const {
        return fmt::format_to(ctx.out(), "{{{}, {}, {}}}", extent.width, extent.height,
                              extent.depth);
    }
};

namespace VideoCommon {

struct ImageBase;
struct ImageViewBase;
struct RenderTargets;

[[nodiscard]] std::string Name(const ImageBase& image);

[[nodiscard]] std::string Name(const ImageViewBase& image_view, GPUVAddr addr);

[[nodiscard]] std::string Name(const RenderTargets& render_targets);

} // namespace VideoCommon
