name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run every hour
    - cron: '7 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v3
        with:
          origin: 'https://git.eden-emu.dev/eden-emu/eden.git'
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
